import Head from 'next/head'
import Image from 'next/image';
import React from 'react';



const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Image src={"/home-bg.jpg"}objectPosition='bottom' objectFit='cover' fill={true} alt="home-bg"/>
      </>
    </>
  )
}
export default Home;
